"""
DNEM Persisted Session Governance v2.0

Loads persisted runtime trial records and executes the full Unified Research
Governance pipeline. Persisted runtime records are provenance-preserving
records; if generated by the deterministic runtime they remain synthetic and
must not be interpreted as empirical validation data.
"""
from __future__ import annotations
from typing import Any, Dict, Optional

from app.governance.live_research_governance_adapter import LiveResearchGovernanceAdapter
from app.governance.unified_research_governance_runtime import UnifiedResearchGovernanceRuntime
from app.services.persistence import Persistence


class PersistedSessionGovernance:
    VERSION = "2.0"

    def __init__(self, db_path="data/dnem.sqlite3", unified_runtime=None):
        self.persistence = Persistence(db_path)
        self.adapter = LiveResearchGovernanceAdapter()
        self.unified = unified_runtime or UnifiedResearchGovernanceRuntime()

    def _load(self, session_id, measurement_id=None):
        trials = self.persistence.list_trials(session_id, measurement_id)
        if not trials:
            raise ValueError("No persisted trial records found for session_id")
        return trials

    def prepare(self, session_id, analysis_id, claim_id, measurement_id=None, **governance_inputs):
        trials = self._load(session_id, measurement_id)
        adapter_keys = {
            "preregistration",
            "exclusion_governance",
            "multiplicity",
            "sensitivity_robustness",
            "validation_gates",
            "evidence_graph",
            "claim_governance",
        }
        adapter_inputs = {k: governance_inputs.get(k) for k in adapter_keys}
        result = self.adapter.prepare(
            trials, analysis_id=analysis_id, claim_id=claim_id, **adapter_inputs
        )
        result["source"] = "PERSISTED_TRIALS"
        result["session_id"] = session_id
        result["persisted_trial_count"] = len(trials)
        result["scientific_boundary"] = {
            "construct_estimates_authorized": False,
            "clinical_inference_authorized": False,
            "synthetic_demo_results_are_not_validation": True,
        }
        return result

    def execute(
        self,
        session_id,
        analysis_id,
        claim_id,
        measurement_id=None,
        study_id=None,
        dataset_id=None,
        **governance_inputs,
    ):
        prepared = self.prepare(
            session_id=session_id,
            analysis_id=analysis_id,
            claim_id=claim_id,
            measurement_id=measurement_id,
            **governance_inputs,
        )

        request = {
            "study_id": study_id or f"STUDY-{session_id}",
            "dataset_id": dataset_id or f"DATASET-{session_id}",
            "analysis_id": analysis_id,
            "claim_id": claim_id,
            "preregistration": governance_inputs.get("preregistration"),
            "exclusion_governance": governance_inputs.get("exclusion_governance"),
            "multiplicity": governance_inputs.get("multiplicity"),
            "effect_uncertainty": governance_inputs.get("effect_uncertainty"),
            "sensitivity_robustness": governance_inputs.get("sensitivity_robustness"),
            "validation_gates": governance_inputs.get("validation_gates"),
            "evidence_graph": governance_inputs.get("evidence_graph"),
            "claim_governance": governance_inputs.get("claim_governance"),
            "claim_type": governance_inputs.get("claim_type", "CANDIDATE"),
            "ledger_context": governance_inputs.get("ledger_context"),
            "model_revision": governance_inputs.get("model_revision"),
        }
        unified = self.unified.execute(request)

        unified["source"] = "PERSISTED_TRIALS"
        unified["session_id"] = session_id
        unified["persisted_trial_count"] = len(self._load(session_id, measurement_id))
        unified["measurement_id"] = measurement_id
        unified["measurement_results"] = prepared.get("measurement_results", [])
        unified["domain_profile"] = prepared.get("domain_profile", {})
        unified["scientific_boundary"] = prepared["scientific_boundary"]
        return unified
